use serde::{Deserialize, Serialize};

use crate::http::request::Request;
use crate::http::response::Response;

#[derive(Serialize)]
struct User
{
    id: u32,
    name: String,
}

#[derive(Deserialize)]
struct CreateUserRequest
{
    name: String,
}

pub fn list_users() -> Response
{
    let users = vec!
    [
        User
        {
            id: 1,
            name: "Stephan".to_string(),
        },
        User
        {
            id: 2,
            name: "Maria".to_string(),
        },
    ];

    let json = serde_json::to_string(&users)
      .expect("[ERROR] Failed to serialize users");

    Response::json(200, "OK", &json)
}

pub fn create_user(request: &Request) -> Response
{
    let payload: CreateUserRequest = match serde_json::from_str(&request.body)
    {
        Ok(payload) => payload,
        Err(_) => 
        {
            return Response::json
            (
                400,
                "BAD REQUEST",
                "{\"error\":\"Invalid JSON payload\"}",
            );
        }
    };

    let user = User
    {
        id: 3, // In a real application, this would be generated by the database
        name: payload.name,
    };

    let json = serde_json::to_string(&user)
        .expect("[ERROR] Failed to serialize created user");
    
    Response::json(201, "CREATED", &json)
}